// Jenkinsfile for updating a local cache of sources and initiating a set of
// builds at once.

node('master') {
  stage('Sync') {
    checkout scm
    dir('.master') {
      sh './sync.sh'
    }
  }

  stage('Trigger Builds') {
    build job: 'riscv-embedded-centos7', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv-embedded-rocky8', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv-embedded-rocky9', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv-embedded-macos', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv-embedded-macos-arm64', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv-embedded-ubuntu1804', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv-embedded-ubuntu2004', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv-embedded-ubuntu2204', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv-embedded-ubuntu2404', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv-embedded-win64', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv-embedded-fullregression', wait: false

    build job: 'riscv64-linux-gcc-centos7', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv64-linux-gcc-rocky8', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv64-linux-gcc-rocky9', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv64-linux-gcc-ubuntu1804', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv64-linux-gcc-ubuntu2004', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv64-linux-gcc-ubuntu2204', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv64-linux-gcc-ubuntu2404', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]

    build job: 'riscv32-gcc-centos7', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv32-gcc-rocky8', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv32-gcc-rocky9', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv32-gcc-macos', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv32-gcc-macos-arm64', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv32-gcc-ubuntu1804', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv32-gcc-ubuntu2004', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv32-gcc-ubuntu2204', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv32-gcc-ubuntu2404', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv32-gcc-win64', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'riscv32-gcc-fullregression', wait: false

    build job: 'riscv32-clang-centos7', wait: false
    build job: 'riscv32-clang-rocky8', wait: false
    build job: 'riscv32-clang-rocky9', wait: false
    build job: 'riscv32-clang-macos', wait: false
    build job: 'riscv32-clang-macos-arm64', wait: false
    build job: 'riscv32-clang-ubuntu1804', wait: false
    build job: 'riscv32-clang-ubuntu2004', wait: false
    build job: 'riscv32-clang-ubuntu2204', wait: false
    build job: 'riscv32-clang-ubuntu2404', wait: false
    build job: 'riscv32-clang-win64', wait: false

    build job: 'or1k-gcc-centos7', wait: false
    build job: 'or1k-gcc-rocky8', wait: false
    build job: 'or1k-gcc-rocky9', wait: false
    build job: 'or1k-gcc-macos', wait: false
    build job: 'or1k-gcc-macos-arm64', wait: false
    build job: 'or1k-gcc-ubuntu1804', wait: false
    build job: 'or1k-gcc-ubuntu2004', wait: false
    build job: 'or1k-gcc-ubuntu2204', wait: false
    build job: 'or1k-gcc-ubuntu2404', wait: false
    build job: 'or1k-gcc-win64', wait: false

    build job: 'gccrs-centos7', wait: false
    build job: 'gccrs-rocky8', wait: false
    build job: 'gccrs-rocky9', wait: false
    build job: 'gccrs-macos', wait: false
    build job: 'gccrs-macos-arm64', wait: false
    build job: 'gccrs-ubuntu1804', wait: false
    build job: 'gccrs-ubuntu2004', wait: false
    build job: 'gccrs-ubuntu2204', wait: false
    build job: 'gccrs-ubuntu2404', wait: false
    build job: 'gccrs-win64', wait: false

    build job: 'gccrs-fsf-centos7', wait: false
    build job: 'gccrs-fsf-rocky8', wait: false
    build job: 'gccrs-fsf-rocky9', wait: false
    build job: 'gccrs-fsf-macos', wait: false
    build job: 'gccrs-fsf-macos-arm64', wait: false
    build job: 'gccrs-fsf-ubuntu1804', wait: false
    build job: 'gccrs-fsf-ubuntu2004', wait: false
    build job: 'gccrs-fsf-ubuntu2204', wait: false
    build job: 'gccrs-fsf-ubuntu2404', wait: false
    build job: 'gccrs-fsf-win64', wait: false

    build job: 'corev-gcc-centos7', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'corev-gcc-macos', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'corev-gcc-macos-arm64', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'corev-gcc-rocky8', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'corev-gcc-rocky9', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'corev-gcc-ubuntu1804', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'corev-gcc-ubuntu2004', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'corev-gcc-ubuntu2204', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
    build job: 'corev-gcc-win64', wait: false, parameters: [booleanParam(name: 'ReducedMultilibTesting', value: true)]
  }
}
